import assert from 'node:assert/strict';
import {newGame,act,validGame,members,missions,canPrestige,payroll,SKILLS,projectScore} from '../src/lib/game.ts';
import {assignmentReadiness} from '../src/lib/scouting-advice.ts';
import {candidatePosition, FIELD_LOCATIONS} from '../src/lib/expedition.ts';
function take(g,a){const next=act(g,a);assert(validGame(next),'Every action preserves a valid save');assert(next.cash>=0);assert(next.actions>=0);return next;}
// Driving routes are covered in field-journey; these fixtures arrive on foot.
function introduce(g,id){if(g.field.met.includes(id))return g;if(g.field.scene==='office')g=take(g,{type:'fieldEnter'});g=take(g,{type:'fieldSnapshot',field:{...g.field,player:candidatePosition(g,id),driving:false}});return take(g,{type:'meet',id});}
function recruit(g,index){let c=g.candidates[index];g=introduce(g,c.id);if(g.actions<2)g=take(g,{type:'nextWeek'});g=take(g,{type:'investigate',id:c.id,method:'interview'});g=take(g,{type:'offer',id:c.id,salary:c.salary,perk:c.motive});assert.equal(members(g).some(x=>x.id===c.id),true);return g;}
function completeCareer(seed){let g=newGame(seed);for(let tier=0;tier<3;tier++){assert.equal(g.tier,tier);assert.throws(()=>act(g,{type:'prestige'}));const picks=tier===0?[0,1,2]:tier===1?[0,1,2,4]:[0,1,2,5];for(const i of picks)g=recruit(g,i);let loops=0;while(!canPrestige(g)){if(++loops>20)throw new Error('Campaign cannot progress');if(g.missionThisWeek||g.actions<1)g=take(g,{type:'nextWeek'});const lineup=members(g).slice(0,3),ids=lineup.map(c=>c.id);const estimate=assignmentReadiness(g,missions(g)[0],lineup);g=take(g,{type:'mission',mission:missions(g)[0].id,ids});assert(g.report.score>=estimate.range[0]&&g.report.score<=estimate.range[1],'Observed results stay inside evidence-only planning estimates');assert(g.report.success,'A well-scouted complementary team succeeds');if(tier===2&&g.exposure>=50&&g.actions>0)g=take(g,{type:'cover'});}const snapshot=JSON.parse(JSON.stringify(g));g=take(g,{type:'prestige'});if(tier<2){assert.equal(g.tier,tier+1);assert.equal(g.history.length,tier+1);assert.equal(members(g).length,0);assert.equal(g.actions,7+tier);assert.equal(g.week,1);}else assert(g.won);assert.equal(snapshot.tier,tier);}return g;}
for(let seed=1;seed<=30;seed++)completeCareer(seed);
let g=newGame(123),original=JSON.stringify(g);
assert.throws(()=>act(g,{type:'scout',source:8}));assert.equal(JSON.stringify(g),original);
const c=g.candidates[0];g=introduce(g,c.id);const cash=g.cash;g=take(g,{type:'offer',id:c.id,salary:c.salary*.85,perk:'none'});assert.equal(g.cash,cash,'Rejected offer refunds all signing costs');assert.equal(g.actions,5);assert.equal(g.candidates[0].status,'available');assert.throws(()=>act(g,{type:'offer',id:c.id,salary:c.salary,perk:'autonomy'}));
g=take(g,{type:'nextWeek'});for(const method of ['interview','sample','reference','trial']){if(g.actions<(method==='trial'?2:1))g=take(g,{type:'nextWeek'});g=take(g,{type:'investigate',id:c.id,method});for(const s of SKILLS){const range=g.candidates[0].ranges[s];if(range)assert(range[0]<=c.skills[s]&&range[1]>=c.skills[s],'Evidence always contains the underlying ability');}}
assert.throws(()=>act(g,{type:'investigate',id:c.id,method:'trial'}));
let deadline=newGame(77);const deadlineId=deadline.candidates[0].id;for(let i=0;i<12;i++)deadline=take(deadline,{type:'nextWeek'});assert.equal(deadline.candidates.find(c=>c.id===deadlineId).status,'rival');deadline=take(deadline,{type:'fieldEnter'});deadline=take(deadline,{type:'fieldSnapshot',field:{...deadline.field,player:FIELD_LOCATIONS[0][1].door}});deadline=take(deadline,{type:'scout',source:0});assert(deadline.candidates.some(c=>c.status==='available'&&c.discovered),'New talent remains discoverable');
let teamGame=newGame(88);teamGame=recruit(teamGame,0);teamGame=recruit(teamGame,1);const wages=payroll(teamGame),before=teamGame.cash;teamGame=take(teamGame,{type:'nextWeek'});assert.equal(teamGame.cash,before+1200-wages);
teamGame=take(teamGame,{type:'mission',mission:'m0',ids:members(teamGame).map(c=>c.id)});assert.throws(()=>act(teamGame,{type:'mission',mission:'m1',ids:members(teamGame).map(c=>c.id)}));assert.equal(members(teamGame)[0].verified,true);
let finished=completeCareer(987);const prestige=finished.prestige;finished=take(finished,{type:'repeat'});assert.equal(finished.tier,2);assert.equal(finished.prestige,prestige);assert.equal(members(finished).length,0);
assert.equal(validGame({version:1}),false);
console.log('PASS: 30 complete three-chapter careers, prestige gates, honest evidence, negotiations, rival deadlines, weekly payroll, assignment limits and restart retention.');
