import assert from 'node:assert/strict';
import { act,newGame,validGame,normalizeGame } from '../src/lib/game.ts';
import { freshImmersion,validImmersion,moveWalker,findLocalWalkPath } from '../src/lib/immersive-runtime.ts';
import { candidateAnchor,getImmersiveLocations } from '../src/lib/immersive-locations.ts';
import { atVenue,canMeet,canRefuel } from '../src/lib/expedition.ts';
const snapshot=(g,patch)=>{const next=act(g,{type:'immersionSnapshot',snapshot:{...structuredClone(g.immersion),...patch}});assert(validGame(next));return next;};
let g=newGame(725);g.story={phase:'complete',choice:null};g.immersion=freshImmersion(g);g.playerProfile={background:'observer'};assert(validGame(g));
const places=getImmersiveLocations(0),maker=places[1],anchor=candidateAnchor(0,'t0-0');
const prior=structuredClone(g.immersion);g=act(g,{type:'setDestination',destination:1});assert.deepEqual(g.immersion.player,prior.player);assert.deepEqual(g.immersion.vehicle,prior.vehicle);
const atDoor=structuredClone(g.immersion);g=act(g,{type:'fieldEnter'});assert.deepEqual(g.immersion,atDoor,'No legacy garage teleport');
g=snapshot(g,{interior:1,player:{...g.immersion.player,...anchor},parkedAt:[0,1]});assert(!atVenue(g,1));assert(!canMeet(g,'t0-0'));assert.throws(()=>act(g,{type:'meet',id:'t0-0'}));assert.throws(()=>act(g,{type:'scout',source:0}));assert(!g.immersion.parkedAt.includes(1),'Walking cannot forge a car arrival');
g=snapshot(g,{vehicle:{...g.immersion.vehicle,...maker.parking,speed:6}});assert(!g.immersion.parkedAt.includes(1),'Passing at speed is not parking');
g=snapshot(g,{vehicle:{...g.immersion.vehicle,speed:0},mode:'foot'});assert(atVenue(g,1));assert(canMeet(g,'t0-0'));
const cash=g.cash,actions=g.actions;g=act(g,{type:'meet',id:'t0-0'});assert.equal(g.cash,cash);assert.equal(g.actions,actions);assert(g.field.met.includes('t0-0'));
g=snapshot(g,{player:{...g.immersion.player,x:maker.door.x,z:maker.door.z+8},interior:1});assert(!canMeet(g,'t0-3'),'Contacts must be found inside');
const physical=structuredClone(g.immersion);g=act(g,{type:'fieldSnapshot',field:{...g.field,player:{x:1,y:1},car:{x:1,y:1}}});assert.deepEqual(g.immersion,physical);assert.notDeepEqual(g.field.player,{x:1,y:1});
g=snapshot(g,{interior:2,player:{...g.immersion.player,x:800,z:500}});assert.equal(g.immersion.interior,null);
const pump=places[4];g=snapshot(g,{interior:null,mode:'foot',player:{...g.immersion.player,x:pump.parking.x+2,z:pump.parking.z},vehicle:{...g.immersion.vehicle,...pump.parking,speed:0,fuel:8}});assert(canRefuel(g));g=act(g,{type:'refuel',gallons:1});assert.equal(g.immersion.vehicle.fuel,9);g=snapshot(g,{vehicle:{...g.immersion.vehicle,fuel:12}});assert.equal(g.immersion.vehicle.fuel,9);
for(const patch of [{mode:'fly'},{interior:9},{tier:2},{parkedAt:[1,1]},{homeReviewed:null},{vehicle:{...g.immersion.vehicle,speed:Infinity}}])assert(!validGame({...g,immersion:{...g.immersion,...patch}}));assert(!validGame({...g,playerProfile:{background:'pilot'}}));assert(validImmersion(g.immersion));assert.deepEqual(normalizeGame(JSON.parse(JSON.stringify(g))),g);
const shelf={minX:100,maxX:101,minZ:100,maxZ:105};assert(moveWalker({x:99,z:102},{x:4,z:0},[shelf]).x<=99.71);assert(moveWalker({x:99,z:99},{x:4,z:-1},[shelf]).x>101);assert(findLocalWalkPath({x:99,z:102},{x:103,z:102},[shelf]).length);assert.deepEqual(findLocalWalkPath({x:10,z:10},{x:900,z:900},[]),[]);
const old=newGame(123);delete old.story;delete old.style;assert(validGame(old));assert.equal(normalizeGame(old).week,1);
const dream=newGame(333);dream.immersion=freshImmersion(dream);dream.field.fuel=10;const awake=act(dream,{type:'story',state:{phase:'wake',choice:null}});assert.equal(awake.immersion.vehicle.fuel,12,'Dream fuel never carries into the real compact');assert.equal(awake.immersion.interior,5);
console.log('PASS: physical first-person arrivals, interior exploration, safe career reloads, real paid fuel, shared furniture collision, local right-click navigation, and dream-to-apartment reset.');
