'use strict';
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs/promises'),syncFS=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module'),crypto=require('node:crypto');
assert.equal(process.platform,'linux','This offscreen diagnostic fixture is Linux-only; use the shipped Mac smoke workflow on Apple silicon.');
const root=path.resolve(__dirname,'../../../..'),main=path.join(root,'electron/main.cjs'),output=path.resolve(__dirname,'../../native-linux');
const meta=JSON.parse(syncFS.readFileSync(path.join(__dirname,'seed-metadata.json'),'utf8'));
const profile=process.env.SCOUT_LINUX_QA_PROFILE;
if(!profile)throw Error('An isolated QA profile is required.');
const phase=process.env.SCOUT_LINUX_QA_PHASE??(process.env.SCOUT_LINUX_QA_REOPEN==='1'?'reopen':'initial');
assert(['initial','reopen','resolve','settled'].includes(phase),'Unknown native QA phase.');
app.setPath('appData',profile);
app.commandLine.appendSwitch('ozone-platform','headless');app.commandLine.appendSwitch('use-angle','swiftshader');app.commandLine.appendSwitch('enable-unsafe-swiftshader');
const report={ok:false,platform:'linux-desktop',scenario:'3.01-active-slow-frames-and-world-polish',electron:process.versions.electron,appVersion:meta.version,checks:[],errors:[],limitations:['Native Linux development build with software SwiftShader; this is not a Mac or Windows native runtime test.','Offscreen window and disabled OS sandbox are confined to the Linux container QA process. Production BrowserWindow security and GPU flags are unchanged.','Mac fullscreen/signature/update installation and Windows installer behavior are not exercised here.','HTTP and HTTPS renderer requests are blocked throughout this isolated fixture; bundled file resources remain available.','Valid synthetic careers are written only into the isolated QA profile. No player career is seeded or replaced.'],metrics:{},screenshots:[]};
let stage='Starting the real native main and preload',window,exitExpected=false,exitBaseline,exitTarget=3,exitScenario='movement';
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const record=(name,data={})=>{report.checks.push({name,passed:true,...data});console.log('PASS '+name);};
const evaluate=code=>window.webContents.executeJavaScript(code,true);
async function until(description,action,timeout=35000){stage=description;const started=Date.now();while(Date.now()-started<timeout){if(report.errors.length)throw Error(report.errors.join('\n'));if(window.isDestroyed()||window.webContents.isDestroyed())throw Error('Native window closed during '+description);if(!window.webContents.isLoadingMainFrame()&&await action())return;await delay(100);}throw Error('Timed out: '+description);}
async function click(selector,text){await until('enabled '+text+' button',()=>evaluate(`(()=>{const button=Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(button=>button.textContent.toLowerCase().includes(${JSON.stringify(text.toLowerCase())}));return !!button&&!button.disabled;})()`));await evaluate(`(()=>{const button=Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(button=>button.textContent.toLowerCase().includes(${JSON.stringify(text.toLowerCase())}));if(!button||button.disabled)throw Error('Expected enabled button');button.click();})()`);}
async function screenshot(name){await delay(150);const image=await window.webContents.capturePage();const file='native-linux-'+name+'.png';await fs.writeFile(path.join(output,file),image.toPNG());report.screenshots.push(file);}
async function probe(){return evaluate(`new Promise(resolve=>requestAnimationFrame(()=>{const canvas=document.querySelector('.scout-immersive-shell canvas'),gl=canvas?.getContext('webgl2');const result={width:canvas?.width||0,height:canvas?.height||0,webgl:!!gl&&!gl.isContextLost(),paintedSamples:0,distinctColors:0};if(!result.webgl)return resolve(result);const debug=gl.getExtension('WEBGL_debug_renderer_info');result.renderer=gl.getParameter(debug?debug.UNMASKED_RENDERER_WEBGL:gl.RENDERER);const pixel=new Uint8Array(4),colors=new Set();for(const y of [.2,.4,.6,.8])for(const x of [.2,.4,.6,.8]){gl.readPixels(Math.floor((gl.drawingBufferWidth-1)*x),Math.floor((gl.drawingBufferHeight-1)*y),1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);if(pixel[3]&&(pixel[0]||pixel[1]||pixel[2]))result.paintedSamples++;colors.add(Array.from(pixel).join(','));}result.distinctColors=colors.size;result.glError=gl.getError();resolve(result);}));`);}
async function read(slot){return JSON.parse(await evaluate(`window.scoutDesktop.loadCareer(${slot})`));}
async function openSettings(){if(!await evaluate("!!document.querySelector('.immersive-settings-modal')")){await evaluate("document.querySelector('[aria-label=\"Open settings (Escape)\"]').click()");}await until('settings modal',()=>evaluate("!!document.querySelector('.immersive-settings-modal')&&!document.querySelector('.immersive-settings-modal').getAttribute('aria-busy')?.includes('true')"));}
async function saveCurrent(slot){await openSettings();await click('.immersive-settings-tabs button','Career backup');await click('.immersive-career-actions button','Save now');await until('durable Save now completion',()=>evaluate("document.querySelector('.immersive-settings-message')?.textContent.includes('Progress saved.')&&document.querySelector('.immersive-settings-modal')?.getAttribute('aria-busy')==='false'"));return read(slot);}
async function resume(){await click('.immersive-resume','Resume');await until('world resumed',()=>evaluate("!document.querySelector('.immersive-settings-modal')"));await delay(250);}
async function title(){await openSettings();await click('.immersive-title-button','Title screen');await until('career title screen',()=>evaluate("!!document.querySelector('.career-slots')&&document.querySelector('.career-setup')?.getAttribute('aria-busy')==='false'"));}
async function loadSlot(slot){await until('enabled native slot '+slot,()=>evaluate(`(()=>{const button=document.querySelectorAll('.career-slot-main')[${slot-1}];return !!button&&!button.disabled&&button.textContent.includes('Linux QA ${slot}');})()`));await evaluate(`document.querySelectorAll('.career-slot-main')[${slot-1}].click()`);await until('full world canvas for slot '+slot,()=>evaluate("(()=>{const canvas=document.querySelector('.scout-immersive-shell canvas');const error=document.querySelector('.immersive-world__error')?.textContent;if(error)throw Error(error);return !!canvas&&canvas.width>=320&&canvas.height>=240&&!document.querySelector('.immersive-world__loading');})()"),120000);await delay(500);}
function input(key,type){window.webContents.sendInputEvent({type,keyCode:key});}
async function hold(key,ms){await evaluate("document.querySelector('canvas')?.focus()");input(key,'keyDown');await delay(ms);input(key,'keyUp');await delay(180);}
async function quality(mode){await openSettings();await click('.immersive-settings-tabs button','Display & comfort');await evaluate(`(()=>{const label=Array.from(document.querySelectorAll('.immersive-quality-modes label')).find(label=>label.textContent.includes(${JSON.stringify(mode)}));if(!label)throw Error('Missing quality option');label.querySelector('input').click();})()`);await delay(300);}
async function installFrameInstrumentation(){await evaluate(`(()=>{if(window.qaRafInstalled)return;window.qaRafInstalled=true;window.qaRafDelayMs=0;window.qaFrameTimes=[];window.qaFrameLast=null;const request=window.requestAnimationFrame.bind(window),cancel=window.cancelAnimationFrame.bind(window);let next=-1;const pending=new Map();window.requestAnimationFrame=callback=>{const id=next--,entry={timer:null,raf:null,active:true};pending.set(id,entry);const schedule=()=>{entry.timer=null;entry.raf=request(timestamp=>{pending.delete(id);if(!entry.active)return;if(window.qaFrameLast!==timestamp){if(window.qaFrameLast!==null)window.qaFrameTimes.push(timestamp-window.qaFrameLast);window.qaFrameLast=timestamp;if(window.qaFrameTimes.length>600)window.qaFrameTimes.shift();}callback(timestamp);});};if(window.qaRafDelayMs>0)entry.timer=setTimeout(schedule,window.qaRafDelayMs);else schedule();return id;};window.cancelAnimationFrame=id=>{const entry=pending.get(id);if(!entry){cancel(id);return;}entry.active=false;if(entry.timer!==null)clearTimeout(entry.timer);if(entry.raf!==null)cancel(entry.raf);pending.delete(id);};})()`);}
async function waitSlowFrames(count){await until('full-scene slow frame sample '+count,()=>evaluate(`window.qaFrameTimes.filter(value=>value>=250).length>=${count}`),75000);}
async function frameMetrics(){return evaluate(`(()=>{const canvas=document.querySelector('.scout-immersive-shell canvas');return {deliberateRafDelayMs:window.qaRafDelayMs,frames:window.qaFrameTimes.length,slowFrames:window.qaFrameTimes.filter(value=>value>=250).length,minMs:Math.min(...window.qaFrameTimes),maxMs:Math.max(...window.qaFrameTimes),meanMs:window.qaFrameTimes.reduce((sum,value)=>sum+value,0)/Math.max(1,window.qaFrameTimes.length),width:canvas?.width,height:canvas?.height,quality:JSON.parse(localStorage.getItem('scout-immersive-preferences-v1')||'{}').graphicsQuality};})()`);}
async function walkToCar(){window.focus();window.webContents.focus();await evaluate("document.querySelector('canvas')?.focus()");input('W','keyDown');try{await until('E correctly offers car entry after fuel and repairs',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.includes('Enter your car')"),45000);}finally{input('W','keyUp');}await delay(180);}
async function interaction(text){await click('.immersive-world__interact button',text);await delay(300);}
async function diagnostics(){const detail={};try{detail.gpuFeatures=app.getGPUFeatureStatus();detail.gpu=await app.getGPUInfo('basic');}catch(error){detail.gpuError=String(error);}try{detail.page=await evaluate("({ready:document.readyState,graphicsError:document.querySelector('.immersive-world__error')?.textContent,body:document.body.innerText.slice(-2200),canvases:Array.from(document.querySelectorAll('canvas')).map(canvas=>({width:canvas.width,height:canvas.height}))})");}catch(error){detail.pageError=String(error);}return detail;}
async function writeReport(){await fs.writeFile(path.join(output,'native-linux-result.json'),JSON.stringify(report,null,2));}
async function prepareHeadlessInput(){await evaluate("HTMLCanvasElement.prototype.requestPointerLock=()=>Promise.reject(new Error('Headless QA has no physical pointer'));window.qaKeys=[];window.addEventListener('keydown',event=>window.qaKeys.push({type:event.type,key:event.key,hidden:document.hidden,trusted:event.isTrusted}));window.addEventListener('keyup',event=>window.qaKeys.push({type:event.type,key:event.key,hidden:document.hidden,trusted:event.isTrusted}));");}
async function replaceAtTitle(slot,career){
  assert(await evaluate("!!document.querySelector('.career-slots')"),'QA careers may only be replaced at the title screen.');
  const saved=await evaluate(`window.scoutDesktop.saveCareer(${JSON.stringify(JSON.stringify(career))},${slot})`);assert.equal(saved.ok,true);
  window.webContents.reload();await until('native title reloads the isolated QA career',()=>evaluate(`document.querySelectorAll('.career-slot-main')[${slot-1}]?.textContent.includes('Linux QA ${slot}')&&!document.querySelectorAll('.career-slot-main')[${slot-1}]?.disabled`));await prepareHeadlessInput();
}
async function quitFromSettings(slot,scenario){exitTarget=slot;exitScenario=scenario;exitBaseline=await read(slot);await openSettings();await screenshot(scenario+'-save-and-exit');exitExpected=true;stage='Native Save and exit preserves '+scenario;await writeReport();await click('.immersive-exit-button','Save and exit');}
function assertPenaltyState(actual,expected){
  for(const key of ['cash','reputation','completed','actions','tier','prestige'])assert.equal(actual[key],expected[key],key+' changed after the incident checkpoint.');
  assert.deepEqual(actual.candidates.map(candidate=>({id:candidate.id,status:candidate.status,trust:candidate.trust,morale:candidate.morale})),expected.candidates.map(candidate=>({id:candidate.id,status:candidate.status,trust:candidate.trust,morale:candidate.morale})), 'Candidate penalties changed after the incident checkpoint.');
}
async function captureSignViews(){
  for(const view of meta.artSeeds){
    await replaceAtTitle(2,view.career);await loadSlot(2);const pixels=await probe();assert(pixels.webgl&&pixels.paintedSamples>0&&pixels.distinctColors>1&&pixels.glError===0);await screenshot(view.name);report.metrics.signViews??=[];report.metrics.signViews.push({name:view.name,sign:view.sign,vehicle:view.career.immersion.vehicle,pixels});await title();
  }
  record('Grounded highway, campus and coast scenes paint for regional art and physical wayfinding review',{views:report.metrics.signViews});
}
async function policeBanner(expected){
  await until('contextual '+expected+' police status',()=>evaluate(`(()=>{const banner=document.querySelector('.immersive-world__police');return !!banner&&banner.dataset.phase===${JSON.stringify(expected)}&&/police/i.test(banner.textContent);})()`),45000);
  const detail=await evaluate("(()=>{const banner=document.querySelector('.immersive-world__police'),bounds=selector=>{const element=document.querySelector(selector);if(!element)return null;const {x,y,width,height,left,right,top,bottom}=element.getBoundingClientRect();return {x,y,width,height,left,right,top,bottom};},rect=bounds('.immersive-world__police'),brand=bounds('.scout-brand'),actions=bounds('.scout-topbar-actions'),overlaps=other=>!!other&&rect.left<other.right&&rect.right>other.left&&rect.top<other.bottom&&rect.bottom>other.top;return {phase:banner.dataset.phase,text:banner.textContent,bounds:rect,brand,actions,overlapsBrand:overlaps(brand),overlapsActions:overlaps(actions)};})()");
  report.metrics.policeBannerBounds??=[];report.metrics.policeBannerBounds.push(detail);assert.equal(detail.overlapsBrand,false,'Contextual police status must not obscure the SCOUT brand.');assert.equal(detail.overlapsActions,false,'Contextual police status must not obscure journal/settings controls.');return detail;
}
async function runPedestrianImpact(){
  await replaceAtTitle(1,meta.impactSeed);await loadSlot(1);await screenshot('community-plaza-before-contact');
  const baseline=await read(1);assertPenaltyState(baseline,meta.impactSeed);assert.equal(baseline.immersion.mode,'driving');
  window.focus();window.webContents.focus();await evaluate("document.querySelector('canvas')?.focus()");input('W','keyDown');
  try{await until('actual W-driven vehicle contact dispatches and durably saves police',async()=>!!(await read(1)).law?.response,180000);}finally{input('W','keyUp');}
  const incident=await read(1);assert.equal(incident.law.sequence,1);assert.equal(incident.law.response.npcId,meta.impactSetup.npcId);assert.equal(incident.law.response.id,'law:1:'+meta.impactSetup.npcId);assert(incident.law.response.speed>=meta.impactSetup.minimumSpeed);assert.equal(incident.law.response.phase,'dispatched');
  assert.equal(incident.cash,baseline.cash-18900);assert.equal(incident.reputation,baseline.reputation-40);assert.equal(incident.completed,baseline.completed-2);assert.equal(incident.actions,0);
  for(const candidate of incident.candidates){const prior=baseline.candidates.find(person=>person.id===candidate.id);assert.equal(candidate.trust,prior.trust-45);if(candidate.status==='hired')assert.equal(candidate.morale,prior.morale-30);}
  assert.equal(incident.tier,baseline.tier);assert.equal(incident.prestige,baseline.prestige);assert.deepEqual(incident.law.last.loss,{fine:18900,reputation:40,missions:2,actions:6,trust:45,morale:30});
  report.metrics.actualPedestrianIncident={setup:meta.impactSetup,incident:incident.law.last,vehicle:incident.immersion.vehicle};record('Actual native W driving strikes the deterministic plaza resident and saves severe career penalties',report.metrics.actualPedestrianIncident);
  report.metrics.dispatchedBanner=await policeBanner('dispatched');await screenshot('pedestrian-ragdoll-and-police-response');
  const pending=await saveCurrent(1);assertPenaltyState(pending,incident);assert(pending.law.response&&pending.law.response.elapsedSeconds<18);report.metrics.pendingBeforeExit=pending.law;record('Police response stays pending while settings pause the live scene');
  await resume();await quitFromSettings(1,'pending-police');
}
async function runLawResolution(){
  const expected=report.metrics.pendingIncidentCareer,reopened=await read(1);assert(expected);assertPenaltyState(reopened,expected);assert.deepEqual(reopened.law,expected.law);assert(reopened.law.response&&!reopened.law.last.resolved);record('A fresh native process preserves pending police time and every immediate career penalty');
  window.setBounds({x:0,y:0,width:640,height:480});await prepareHeadlessInput();await loadSlot(1);await policeBanner(reopened.law.response.phase);const viewport=await probe();assert(viewport.webgl&&viewport.paintedSamples>0&&viewport.distinctColors>1);await screenshot('pending-police-reopened');
  // The save resumes its car at rest. Use the actual exit and drag-look handlers,
  // then walk toward the road while the response advances; never move the camera
  // above the scenery to reduce graphics work or teleport the scene for a capture.
  await interaction('step out');await until('driver is on foot beside the real compact',async()=>{const career=await read(1);return career.immersion.mode==='foot'&&!await evaluate("document.querySelector('.immersive-world__interact button')?.textContent.toLowerCase().includes('step out')");});
  await evaluate("document.querySelector('canvas')?.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,buttons:1,movementX:-Math.PI/.00175,movementY:0}))");
  window.focus();window.webContents.focus();await evaluate("document.querySelector('canvas')?.focus()");input('W','keyDown');
  try{await until('real active simulation brings police and officer to the collision scene',async()=>{const career=await read(1);return career.law?.response?.phase==='arrived'&&career.law.response.elapsedSeconds>=20;},600000);}finally{input('W','keyUp');}
  report.metrics.arrivedBanner=await policeBanner('arrived');await screenshot('police-arrival');const arrived=await saveCurrent(1);assert(arrived.law.response.elapsedSeconds>=18&&arrived.law.response.elapsedSeconds<30);assertPenaltyState(arrived,expected);record('Actual resumed fixed simulation advances persistent police response to arrival',{response:arrived.law.response});await resume();
  await until('real active police response impounds the vehicle',async()=>{const career=await read(1);return career.law?.response===null&&career.law?.last?.resolved;},600000);
  await until('settled first-person scene adopts the impounded foot pose',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.includes('Enter your car')"),60000);
  await screenshot('police-impound');const settled=await saveCurrent(1);assertPenaltyState(settled,expected);assert.equal(settled.law.sequence,1);assert.equal(settled.law.response,null);assert.equal(settled.law.last.resolved,true);assert.equal(settled.immersion.mode,'foot');
  const before=arrived.immersion.vehicle,car=settled.immersion.vehicle,station=meta.services.reduce((nearest,point)=>Math.hypot(before.x-point.parking.x,before.z-point.parking.z)<Math.hypot(before.x-nearest.parking.x,before.z-nearest.parking.z)?point:nearest);
  assert.equal(car.x,station.parking.x);assert.equal(car.z,station.parking.z);assert.equal(car.speed,0);assert.equal(car.gear,before.gear);assert.equal(car.disabled,before.disabled);assert.equal(settled.immersion.destination,arrived.immersion.destination);assert.equal(car.damage,before.damage);
  assert(car.distance>=before.distance&&car.distance-before.distance<.5,'Impound must retain mileage rather than reset it.');assert(car.fuel<=before.fuel&&before.fuel-car.fuel<.1,'Impound must preserve fuel rather than grant a full tank.');
  report.metrics.nativePoliceImpound={before,after:car,station:station.id,law:settled.law};record('Native police resolution preserves penalties and impounds at the nearest service without free repairs, fuel or mileage reset',report.metrics.nativePoliceImpound);
  await resume();await quitFromSettings(1,'resolved-police');
}
async function runSettledReopen(){
  const expected=report.metrics.settledIncidentCareer,reopened=await read(1);assert(expected);assertPenaltyState(reopened,expected);assert.deepEqual(reopened.law,expected.law);assert.equal(reopened.law.response,null);assert.equal(reopened.law.last.resolved,true);assert.deepEqual(reopened.immersion,expected.immersion);record('A third fresh native process retains the resolved incident and final impound checkpoint');
  window.setBounds({x:0,y:0,width:640,height:480});await prepareHeadlessInput();await loadSlot(1);await delay(1200);await screenshot('settled-police-reopened');const saved=await saveCurrent(1);assertPenaltyState(saved,expected);assert.deepEqual(saved.law,expected.law);assert.equal(await evaluate("!!document.querySelector('.immersive-world__police')"),false);record('Resuming and re-saving a resolved police incident does not reopen it or charge the career twice');
  await title();await runSameChapterRestart();await loadSlot(1);await quitFromSettings(1,'settled-police');
}
async function runSameChapterRestart(){
  const untouched=await Promise.all([evaluate('window.scoutDesktop.loadCareer(1)'),evaluate('window.scoutDesktop.loadCareer(3)')]);
  await replaceAtTitle(2,meta.restartSeed);await loadSlot(2);await evaluate("window.qaRestartCanvas=document.querySelector('.scout-immersive-shell canvas')");
  await click('.scout-topbar-actions button','Journal');await click('.scout-journal-tabs button','Career');await click('.gp-modal-career button','Restart this chapter');await until('explicit same-chapter restart confirmation',()=>evaluate("document.querySelector('.gp-confirm h3')?.textContent==='Restart this chapter?'"));await screenshot('chapter-restart-confirm');
  await click('.gp-confirm button','Confirm restart');await until('same-chapter restart creates a ready replacement world',()=>evaluate("(()=>{const canvas=document.querySelector('.scout-immersive-shell canvas');return !!document.querySelector('.gp-modal-briefing')&&!!canvas&&canvas!==window.qaRestartCanvas&&!window.qaRestartCanvas.isConnected&&document.querySelectorAll('.scout-immersive-shell canvas').length===1&&!document.querySelector('.immersive-world__loading');})()"),120000);
  await until('new chapter reset is durable',async()=>{const game=await read(2);return game.briefing&&game.completed===0&&game.immersion.vehicle.distance===0&&game.immersion.interior===meta.restartExpected.immersion.interior;});
  const reset=await read(2),expected=meta.restartExpected;for(const key of ['tier','prestige','week','cash','reputation','completed','attempts','actions','briefing'])assert.equal(reset[key],expected[key]);assert.deepEqual(reset.candidates,expected.candidates);assert.deepEqual(reset.history,expected.history);assert.deepEqual(reset.immersion,expected.immersion);assert.equal(reset.story.phase,'complete');assert.equal(reset.candidates.filter(candidate=>candidate.status==='hired').length,0);
  report.metrics.sameChapterRestart={before:meta.restartSeed.immersion,reset:reset.immersion,replacedCanvas:true};record('Confirmed same-chapter restart remounts the live world and durably resets its vehicle, position and team',report.metrics.sameChapterRestart);
  await click('.gp-modal-briefing button','Enter the office');await until('restart briefing dismissed',()=>evaluate("!document.querySelector('.gp-modal-briefing')"));const pixels=await probe();assert(pixels.webgl&&pixels.paintedSamples>0&&pixels.distinctColors>1&&pixels.glError===0);await screenshot('chapter-restart-headquarters');
  await hold('D',3500);const moved=await saveCurrent(2);assert.equal(moved.immersion.interior,expected.immersion.interior);assert(Math.hypot(moved.immersion.player.x-expected.immersion.player.x,moved.immersion.player.z-expected.immersion.player.z)>.2,'Actual WASD must move the recreated character from the fresh headquarters spawn.');assert(Math.hypot(moved.immersion.player.x-meta.restartSeed.immersion.player.x,moved.immersion.player.z-meta.restartSeed.immersion.player.z)>100,'A live flush must not restore the previous station scene after restart.');assert.deepEqual(moved.immersion.vehicle,expected.immersion.vehicle);report.metrics.sameChapterRestart.afterInput=moved.immersion;record('Actual keyboard movement and a live save remain in the restarted chapter rather than restoring the old scene',{player:moved.immersion.player,vehicle:moved.immersion.vehicle});await title();
  const after=await Promise.all([evaluate('window.scoutDesktop.loadCareer(1)'),evaluate('window.scoutDesktop.loadCareer(3)')]);assert.deepEqual(after,untouched);record('Slot-2 chapter restart preserves the resolved law career and the unrelated final movement career byte for byte');await evaluate('delete window.qaRestartCanvas');
}
async function run(){
 try{
  await fs.mkdir(output,{recursive:true});await until('native career menu',()=>evaluate("!!document.querySelector('.career-slots')&&document.querySelector('.career-setup')?.getAttribute('aria-busy')==='false'"));
  if(phase!=='initial'){const prior=JSON.parse(await fs.readFile(path.join(output,'native-linux-result.json'),'utf8'));assert.equal(prior.ok,true);assert.equal(report.distHTMLSHA256,prior.distHTMLSHA256,'All native phases must use the same coordinated production renderer.');assert.equal(report.sourceMainSHA256,prior.sourceMainSHA256,'All native phases must use the same native main source.');Object.assign(report,prior);report.ok=false;report.errors=[];delete report.error;delete report.completedPhase;}
  if(phase==='resolve'){await runLawResolution();return;}
  if(phase==='settled'){await runSettledReopen();return;}
  if(phase==='reopen'){
    const slots=await evaluate('window.scoutDesktop.listSaveSlots()');assert.equal(slots.length,3);assert(slots.every(slot=>slot.occupied));
    const reopened=await read(3);assert.deepEqual(reopened.immersion,report.metrics.finalCareer);record('A fresh native process reloads the final durable career through the real preload');
    window.setBounds({x:0,y:0,width:640,height:480});await loadSlot(3);const viewport=await probe();assert(viewport.webgl&&viewport.paintedSamples>0&&viewport.distinctColors>1&&viewport.glError===0);report.metrics.reopenedViewport=viewport;record('Reopened career enters and paints the actual saved first-person world');await screenshot('reopened');
    await click('.immersive-world__tools button','Map');await click('.immersive-world__map button','Nearby');const nearby=await evaluate("Array.from(document.querySelectorAll('.map-place')).map(button=>({name:button.getAttribute('title'),left:parseFloat(button.style.left),top:parseFloat(button.style.top)}))");const player=reopened.immersion.player,origin={x:Math.max(0,Math.min(meta.world.width-2400,player.x-1200)),z:Math.max(0,Math.min(meta.world.depth-2000,player.z-1000))};const expected=meta.venues.filter(venue=>venue.parking.x>=origin.x&&venue.parking.x<=origin.x+2400&&venue.parking.z>=origin.z&&venue.parking.z<=origin.z+2000);assert.equal(nearby.length,expected.length);for(const venue of expected){const pin=nearby.find(pin=>pin.name===venue.name);assert(pin);assert(Math.abs(pin.left-(venue.parking.x-origin.x)/2400*100)<.01);assert(Math.abs(pin.top-(venue.parking.z-origin.z)/2000*100)<.01);}record('Nearby map clips distant venues and maps the real 2.4 km by 2 km viewport',{places:nearby,origin});await screenshot('reopened-nearby-map');await evaluate("document.querySelector('[aria-label=\"Close map\"]').click()");report.reopenObserved=true;await title();await captureSignViews();await runPedestrianImpact();return;
  }
  window.setBounds({x:0,y:0,width:1280,height:800});
  assert.equal(await evaluate('window.scoutDesktop.platform'),'linux-desktop');const slots=await evaluate('window.scoutDesktop.listSaveSlots()');assert.equal(slots.length,3);assert(slots.every(slot=>!slot.occupied));record('Real sandbox preload exposes three empty isolated native save slots');await screenshot('title');
  for(let slot=1;slot<=3;slot++){const saved=await evaluate(`window.scoutDesktop.saveCareer(${JSON.stringify(JSON.stringify(meta.seeds[slot-1]))},${slot})`);assert.equal(saved.ok,true);assert.equal((await read(slot)).style.name,'Linux QA '+slot);}record('Three schema-2 careers write and reload through the real native save store');
  await evaluate("localStorage.setItem('scout-immersive-preferences-v1',JSON.stringify({graphicsQuality:'auto'}))");window.webContents.reload();await until('seeded native careers ready after reload',()=>evaluate("document.querySelector('.career-slot-main')?.textContent.includes('Linux QA 1')&&!document.querySelector('.career-slot-main')?.disabled"));
  await prepareHeadlessInput();report.limitations.push('Pointer capture is unavailable in the offscreen fixture; its request rejects immediately. Native mouse locking is not exercised.');
  window.setBounds({x:0,y:0,width:640,height:480});
  await installFrameInstrumentation();await loadSlot(1);const viewport=await probe();assert(viewport.webgl&&viewport.width>=320&&viewport.height>=240);assert.equal(viewport.glError,0);assert(viewport.paintedSamples>0&&viewport.distinctColors>1);report.metrics.viewport=viewport;record('Actual first-person world paints distinct visible WebGL2 pixels',viewport);await screenshot('on-foot');
  const initialRaw=await evaluate('window.scoutDesktop.loadCareer(1)');await interaction('Enter your car');await until('actual cockpit mode',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.toLowerCase().includes('step out')"));
  const clutter=await evaluate("({floatingDrivingHUD:!!document.querySelector('.immersive-world__driving'),floatingMph:!!document.querySelector('.immersive-world__speed'),floatingFuel:!!document.querySelector('.immersive-world__fuel'),localStorageCopy:document.querySelector('.scout-topbar')?.textContent.includes('locally'),fieldNotes:!!document.querySelector('.scout-quiet-objective')})");assert(Object.values(clutter).every(value=>value===false));record('Cockpit has no floating mph/fuel gauges or permanent storage/objective clutter',clutter);await screenshot('cockpit');
  await quality('Detail');await quality('Automatic');await until('automatic quality reset at the full CSS size',()=>evaluate("document.querySelector('.scout-immersive-shell canvas')?.width>=640"));const qualityStart=await frameMetrics();await resume();
  report.limitations.push('Active slow-frame regression deliberately delays renderer requestAnimationFrame scheduling by 300 ms. The normal grounded/cockpit scene remains visible during all input checks. These are simulation/quality/governor assertions under Linux software rendering, not target-hardware frame-rate measurements.');
  await evaluate('window.qaFrameTimes=[];window.qaFrameLast=null;window.qaRafDelayMs=300');window.focus();window.webContents.focus();await evaluate("document.querySelector('canvas').focus()");input('W','keyDown');await waitSlowFrames(12);input('A','keyDown');await waitSlowFrames(18);input('A','keyUp');input('W','keyUp');await delay(250);const qualityEnd=await frameMetrics();report.metrics.activeSlowFrames={start:qualityStart,end:qualityEnd};report.metrics.keyboardEvents=await evaluate('window.qaKeys');await screenshot('active-slow-frames');await evaluate('window.qaRafDelayMs=0');
  assert(qualityEnd.slowFrames>=18);assert(qualityEnd.width<qualityStart.width&&qualityEnd.height<qualityStart.height,'Automatic quality must adapt even when active frames exceed 250 ms.');assert(qualityEnd.width>=320&&qualityEnd.height>=240,'Adaptive quality must retain its configured readability floor.');record('Automatic quality reduces full-scene backing pixels during sustained active slow frames',report.metrics.activeSlowFrames);
  assert.equal(await evaluate('window.scoutDesktop.loadCareer(1)'),initialRaw);record('Live driving snapshots do not write the career every few seconds');
  const moving=await saveCurrent(1);assert.equal(moving.immersion.mode,'driving');assert(moving.immersion.vehicle.distance>1);assert(moving.immersion.vehicle.fuel<12);assert(Math.abs(moving.immersion.vehicle.heading)>.01);assert(Math.abs(moving.immersion.vehicle.speed)>.1);record('Native keyboard acceleration and steering produce real distance, fuel use and heading changes',{vehicle:moving.immersion.vehicle});record('Sustained active frames over 250 ms continue bounded simulation rather than freezing it',{slowFrames:qualityEnd.slowFrames,distance:moving.immersion.vehicle.distance,fuel:moving.immersion.vehicle.fuel,heading:moving.immersion.vehicle.heading});await screenshot('settings');
  input('W','keyDown');await delay(2200);input('W','keyUp');const paused=await saveCurrent(1);assert.deepEqual(paused.immersion.vehicle,moving.immersion.vehicle);record('Settings pause discards held input and does not advance vehicle state');await resume();await delay(500);const resumed=await saveCurrent(1);assert(resumed.immersion.vehicle.distance-moving.immersion.vehicle.distance<Math.max(4,moving.immersion.vehicle.speed*1.5));record('Resuming a paused scene does not repay the unseen pause as a simulation jump',{distanceBefore:moving.immersion.vehicle.distance,distanceAfter:resumed.immersion.vehicle.distance});await resume();
  input('S','keyDown');await delay(300);input('S','keyUp');input('SPACE','keyDown');try{await until('handbrake brings the visible car to its exit speed',()=>evaluate("!!document.querySelector('.immersive-world__interact button')?.textContent.toLowerCase().includes('step out')"),30000);}finally{input('SPACE','keyUp');}await delay(350);await interaction('step out');await until('driver can step out after stopping',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.includes('Enter your car')"));await screenshot('after-drive-exterior');
  const stopped=await saveCurrent(1);assert.equal(stopped.immersion.mode,'foot');assert.equal(stopped.immersion.vehicle.speed,0);assert(stopped.immersion.vehicle.distance>=moving.immersion.vehicle.distance);record('Brake, handbrake and grounded car exit preserve the driven career');await resume();
  await click('.immersive-world__tools button','Map');await until('regional map dialog',()=>evaluate("!!document.querySelector('.immersive-world__map')"));
  const map=await evaluate(`(()=>{const places=Array.from(document.querySelectorAll('.map-place')).map(button=>({name:button.getAttribute('title'),left:parseFloat(button.style.left),top:parseFloat(button.style.top)}));return {places,services:document.querySelectorAll('.map-service').length,regions:document.querySelectorAll('.map-region').length,nearbyToggle:Array.from(document.querySelectorAll('.immersive-world__map button')).some(button=>button.textContent.includes('Nearby'))};})()`);for(const venue of meta.venues){const pin=map.places.find(pin=>pin.name===venue.name);assert(pin,'Missing '+venue.name+' map pin');assert(Math.abs(pin.left-venue.parking.x/meta.world.width*100)<.01);assert(Math.abs(pin.top-venue.parking.z/meta.world.depth*100)<.01);}assert.equal(map.services,meta.services.filter(station=>station.locationId<0).length);assert(map.regions>=7&&map.nearbyToggle);record('Regional map uses the real 12 km by 10 km bounds and shows service destinations',map);await screenshot('regional-map');
  await click('.immersive-world__map button','Nearby');await screenshot('nearby-map');await evaluate("document.querySelector('[aria-label=\"Close map\"]').click()");await title();await loadSlot(1);const reloaded=await read(1);assert.deepEqual(reloaded.immersion.vehicle,stopped.immersion.vehicle);record('Save, title and career reload retain vehicle pose, fuel, damage and mileage');await title();
  await loadSlot(2);await interaction('Refuel');await until('physical pump service dialog',()=>evaluate("!!document.querySelector('.immersive-world__service')"));await screenshot('service');await click('.immersive-world__service-actions button','Fill the tank');await until('fuel purchase dialog closes',()=>evaluate("!document.querySelector('.immersive-world__service')"));const filled=await saveCurrent(2);assert.equal(filled.immersion.vehicle.fuel,12);assert.equal(filled.immersion.vehicle.damage,.42);assert.equal(filled.immersion.vehicle.distance,1523.4);assert(filled.cash<meta.seeds[1].cash);record('Fuel is purchased at the modeled pump without repairing damage or resetting mileage');await resume();
  await interaction('Refuel');await click('.immersive-world__service-actions button','Repair the compact');await until('repair dialog closes',()=>evaluate("!document.querySelector('.immersive-world__service')"));const repaired=await saveCurrent(2);assert.equal(repaired.immersion.vehicle.damage,0);assert.equal(repaired.immersion.vehicle.disabled,false);assert.equal(repaired.immersion.vehicle.distance,1523.4);assert.equal(repaired.immersion.vehicle.fuel,12);assert(repaired.cash<filled.cash);record('Paid repairs restore vehicle condition while keeping fuel and mileage');await resume();
  await walkToCar();await interaction('Enter your car');const entered=await saveCurrent(2);assert.equal(entered.immersion.mode,'driving');assert.equal(entered.immersion.vehicle.fuel,12);record('E prompt matches its action and the car can be re-entered after pump service');await resume();await screenshot('service-reentered-cockpit');await title();
  await loadSlot(3);await until('stranded roadside assistance prompt',()=>evaluate("!!document.querySelector('.immersive-world__roadside')"));await screenshot('stranded');input('T','keyDown');input('T','keyUp');await until('native tow checkpoint',async()=>{const raw=await read(3);return raw.cash<meta.seeds[2].cash&&Math.hypot(raw.immersion.vehicle.x-meta.seeds[2].immersion.vehicle.x,raw.immersion.vehicle.z-meta.seeds[2].immersion.vehicle.z)>30;});const towed=await saveCurrent(3);assert.equal(towed.cash,meta.seeds[2].cash-150);assert.equal(towed.immersion.vehicle.distance,3142.7);assert.equal(towed.immersion.vehicle.fuel,2.25);assert.equal(towed.immersion.vehicle.damage,.93);assert.equal(towed.immersion.vehicle.disabled,true);assert.equal(towed.immersion.vehicle.gear,'R');assert.equal(towed.immersion.mode,'foot');record('Actual T roadside tow charges $150 and preserves fuel, damage, gear and mileage',{vehicle:towed.immersion.vehicle});await resume();await screenshot('towed');
  exitBaseline=await read(3);await hold('D',8000);await evaluate("window.dispatchEvent(new Event('scout:flush-field'))");assert.deepEqual((await read(3)).immersion.player,exitBaseline.immersion.player);record('Final walking movement remains live until the exit checkpoint');
  report.metrics.updateStatus=await evaluate('window.scoutDesktop.getUpdateStatus()');assert.equal(report.metrics.updateStatus.state,'unsupported');record('Linux development update manager does not block the offline local world',{state:report.metrics.updateStatus.state});
  report.diagnostics=await diagnostics();assert.deepEqual(report.errors,[]);await openSettings();await screenshot('save-and-exit');exitExpected=true;stage='Save and exit persists the newest live world snapshot';await writeReport();await click('.immersive-exit-button','Save and exit');
 }catch(error){report.ok=false;report.stage=stage;report.error=String(error.stack||error);try{report.diagnostics=await diagnostics();report.metrics.finalKeys=await evaluate('window.qaKeys');await screenshot('failure');}catch(captureError){report.captureError=String(captureError);}await writeReport();console.error(report.error);app.exit(1);}
}
app.on('ready',()=>console.log('QA Electron ready'));
app.on('browser-window-created',(_event,created)=>{
  console.log('QA real native window created');window=created;
  created.webContents.session.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(details,callback)=>{report.metrics.blockedExternalHosts??=[];const host=new URL(details.url).hostname;if(!report.metrics.blockedExternalHosts.includes(host))report.metrics.blockedExternalHosts.push(host);callback({cancel:true});});
  created.webContents.on('dom-ready',()=>console.log('QA renderer DOM ready'));created.webContents.on('preload-error',(_event,_path,error)=>report.errors.push('Preload: '+error));created.webContents.on('did-fail-load',(_event,code,description,_url,mainFrame)=>{if(mainFrame&&code!==-3)report.errors.push('Load '+code+': '+description);});created.webContents.on('render-process-gone',(_event,details)=>report.errors.push('Renderer: '+details.reason));created.webContents.on('console-message',({level,message})=>{if(level==='error'||level===3)report.errors.push(message);});created.once('ready-to-show',()=>{console.log('QA real native window ready to show');void run();});
});
app.on('child-process-gone',(_event,details)=>{if(details.type==='GPU'&&!['normal-exit','clean-exit'].includes(details.reason))report.errors.push('GPU: '+details.reason);});
app.on('will-quit',()=>{
  if(!exitExpected)return;
  try{
    const raw=JSON.parse(syncFS.readFileSync(path.join(app.getPath('userData'),'save','slot-'+exitTarget,'career.json'),'utf8'));
    if(exitScenario==='movement'){
      assert(Math.hypot(raw.immersion.player.x-exitBaseline.immersion.player.x,raw.immersion.player.z-exitBaseline.immersion.player.z)>.2,'Save and exit must save the movement after the last checkpoint.');
      for(const key of ['fuel','damage','distance'])assert.equal(raw.immersion.vehicle[key],exitBaseline.immersion.vehicle[key]);
      assert.equal(raw.immersion.mode,'foot');report.metrics.finalCareer=raw.immersion;record('Real native Save and exit flushes the latest movement before app shutdown');
    }else{
      assertPenaltyState(raw,exitBaseline);assert.equal(raw.law.sequence,exitBaseline.law.sequence);assert.equal(raw.law.last.id,exitBaseline.law.last.id);
      if(exitScenario==='pending-police'){
        assert(raw.law.response&&raw.law.response.elapsedSeconds<30,'Quitting must retain the active police response.');assert.equal(raw.law.last.resolved,false);report.metrics.pendingIncidentCareer=raw;record('Native Save and exit retains the active police response and its immediate penalties');
      }else{
        assert.equal(raw.law.response,null);assert.equal(raw.law.last.resolved,true);report.metrics.settledIncidentCareer=raw;record(exitScenario==='settled-police'?'Final native shutdown does not charge a resolved incident twice':'Native Save and exit retains the resolved incident and impounded vehicle');
      }
    }
    assert.deepEqual(report.errors,[]);report.nativeQuitObserved=true;report.ok=true;report.stage='Completed';report.completedPhase=phase;
  }catch(error){report.ok=false;report.error=String(error.stack||error);report.stage=stage;}
  syncFS.writeFileSync(path.join(output,'native-linux-result.json'),JSON.stringify(report,null,2));
});
const source=syncFS.readFileSync(main,'utf8');assert.equal((source.match(/webPreferences: \{/g)||[]).length,1);report.sourceMainSHA256=hash(source);report.distHTMLSHA256=hash(syncFS.readFileSync(path.join(root,'dist/index.html')));
assert.equal((source.match(/app\.requestSingleInstanceLock\(\)/g)||[]).length,1);report.limitations.push('The test bypasses the single-instance OS socket lock in memory because this Linux container blocks socket creation. Single-instance locking is not exercised.');
assert.equal((source.match(/screen\.getCursorScreenPoint\(\)/g)||[]).length,1);report.limitations.push('The headless fixture supplies a fixed cursor position because the headless Linux Ozone surface has no physical pointer. Desktop pointer and monitor selection are not exercised.');
report.limitations.push('A synthetic 1280 by 800 monitor is supplied in memory to the headless fixture. Physical display selection and fullscreen transitions are not exercised.');
const monitorExpression='({bounds:{x:0,y:0,width:1280,height:800},workArea:{x:0,y:0,width:1280,height:800}})';
report.limitations.push('Native titlebar options are omitted in the offscreen Linux fixture; OS titlebar styling is not exercised.');
const virtualSource=source.replace('webPreferences: {','webPreferences: { offscreen: true, backgroundThrottling: false,').replace('app.requestSingleInstanceLock()','true').replace('screen.getDisplayNearestPoint(screen.getCursorScreenPoint())',monitorExpression).replace('window: mainWindow, screen, preferences:','window: mainWindow, screen: {getDisplayMatching: () => '+monitorExpression+'}, preferences:').replace('...titleBarOptions(),','frame: false,').replace('function createWindow() {',"function createWindow() {console.log('QA enter real createWindow');").replace('const bounds = initialDisplay.mode',"console.log('QA monitor selected');const bounds = initialDisplay.mode").replace('mainWindow = new BrowserWindow({',"console.log('QA constructing native window');mainWindow = new BrowserWindow({").replace('const menu = applicationMenu',"console.log('QA beginning native services');const menu = applicationMenu").replace('registerBridge();',"console.log('QA registering native bridge');registerBridge();").replace('createWindow();',"console.log('QA services ready');createWindow();");const realMain=new Module(main,module);realMain.filename=main;realMain.paths=Module._nodeModulePaths(path.dirname(main));realMain._compile(virtualSource,main);
