'use strict';
const {app,BrowserWindow}=require('electron');
const fs=require('node:fs/promises'),syncFS=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),Module=require('node:module'),crypto=require('node:crypto');
assert.equal(process.platform,'linux','This offscreen diagnostic fixture is Linux-only; use the shipped Mac smoke workflow on Apple silicon.');
const root=path.resolve(__dirname,'../../../..'),main=path.join(root,'electron/main.cjs'),output=path.resolve(__dirname,'../qa301');
const meta=JSON.parse(syncFS.readFileSync(path.join(__dirname,'seed-metadata.json'),'utf8'));
const profile=process.env.SCOUT_LINUX_QA_PROFILE;
if(!profile)throw Error('An isolated QA profile is required.');
app.setPath('appData',profile);
app.commandLine.appendSwitch('ozone-platform','headless');app.commandLine.appendSwitch('use-angle','swiftshader');app.commandLine.appendSwitch('enable-unsafe-swiftshader');
const report={ok:false,platform:'linux-desktop',electron:process.versions.electron,appVersion:meta.version,checks:[],errors:[],limitations:['Native Linux development build with software SwiftShader; this is not a Mac or Windows native runtime test.','Offscreen window and disabled OS sandbox are confined to the Linux container QA process. Production BrowserWindow security and GPU flags are unchanged.','Mac fullscreen/signature/update installation and Windows installer behavior are not exercised here.'],metrics:{},screenshots:[]};
let stage='Starting the real native main and preload',window,exitExpected=false,exitBaseline;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const record=(name,data={})=>{report.checks.push({name,passed:true,...data});console.log('PASS '+name);};
const evaluate=code=>window.webContents.executeJavaScript(code,true);
async function until(description,action,timeout=35000){stage=description;const started=Date.now();while(Date.now()-started<timeout){if(report.errors.length)throw Error(report.errors.join('\n'));if(window.isDestroyed()||window.webContents.isDestroyed())throw Error('Native window closed during '+description);if(!window.webContents.isLoadingMainFrame()&&await action())return;await delay(100);}throw Error('Timed out: '+description);}
async function click(selector,text){await until('enabled '+text+' button',()=>evaluate(`(()=>{const button=Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(button=>button.textContent.toLowerCase().includes(${JSON.stringify(text.toLowerCase())}));return !!button&&!button.disabled;})()`));await evaluate(`(()=>{const button=Array.from(document.querySelectorAll(${JSON.stringify(selector)})).find(button=>button.textContent.toLowerCase().includes(${JSON.stringify(text.toLowerCase())}));if(!button||button.disabled)throw Error('Expected enabled button');button.click();})()`);}
async function screenshot(name){await delay(150);const image=await window.webContents.capturePage();const file='native-linux-'+name+'.png';await fs.writeFile(path.join(output,file),image.toPNG());report.screenshots.push(file);}
async function probe(){return evaluate(`new Promise(resolve=>requestAnimationFrame(()=>{const canvas=document.querySelector('.scout-immersive-shell canvas'),gl=canvas?.getContext('webgl2');const result={width:canvas?.width||0,height:canvas?.height||0,webgl:!!gl&&!gl.isContextLost(),paintedSamples:0,distinctColors:0};if(!result.webgl)return resolve(result);const debug=gl.getExtension('WEBGL_debug_renderer_info');result.renderer=gl.getParameter(debug?debug.UNMASKED_RENDERER_WEBGL:gl.RENDERER);const pixel=new Uint8Array(4),colors=new Set();for(const y of [.2,.4,.6,.8])for(const x of [.2,.4,.6,.8]){gl.readPixels(Math.floor((gl.drawingBufferWidth-1)*x),Math.floor((gl.drawingBufferHeight-1)*y),1,1,gl.RGBA,gl.UNSIGNED_BYTE,pixel);if(pixel[3]&&(pixel[0]||pixel[1]||pixel[2]))result.paintedSamples++;colors.add(Array.from(pixel).join(','));}result.distinctColors=colors.size;result.glError=gl.getError();resolve(result);}));`);}
async function read(slot){return JSON.parse(await evaluate(`window.scoutDesktop.loadCareer(${slot})`));}
async function openSettings(){if(!await evaluate("!!document.querySelector('.immersive-settings-modal')")){await evaluate("document.querySelector('[aria-label=\"Open settings (Escape)\"]').click()");}await until('settings modal',()=>evaluate("!!document.querySelector('.immersive-settings-modal')&&!document.querySelector('.immersive-settings-modal').getAttribute('aria-busy')?.includes('true')"));}
async function saveCurrent(slot){await openSettings();await click('.immersive-settings-tabs button','Career backup');await click('.immersive-career-actions button','Save now');await until('durable Save now completion',()=>evaluate("document.querySelector('.immersive-settings-message')?.textContent.includes('Progress saved.')&&document.querySelector('.immersive-settings-modal')?.getAttribute('aria-busy')==='false'"));return read(slot);}
async function resume(){await click('.immersive-resume','Resume');await until('world resumed',()=>evaluate("!document.querySelector('.immersive-settings-modal')"));await delay(250);}
async function title(){await openSettings();await click('.immersive-title-button','Title screen');await until('career title screen',()=>evaluate("!!document.querySelector('.career-slots')&&document.querySelector('.career-setup')?.getAttribute('aria-busy')==='false'"));}
async function loadSlot(slot){await until('enabled native slot '+slot,()=>evaluate(`(()=>{const button=document.querySelectorAll('.career-slot-main')[${slot-1}];return !!button&&!button.disabled&&button.textContent.includes('Linux QA ${slot}');})()`));await evaluate(`document.querySelectorAll('.career-slot-main')[${slot-1}].click()`);await until('full world canvas for slot '+slot,()=>evaluate("(()=>{const canvas=document.querySelector('.scout-immersive-shell canvas');const error=document.querySelector('.immersive-world__error')?.textContent;if(error)throw Error(error);return !!canvas&&canvas.width>=640&&canvas.height>=480&&!document.querySelector('.immersive-world__loading');})()"),60000);await delay(500);}
function input(key,type){window.webContents.sendInputEvent({type,keyCode:key});}
async function hold(key,ms){await evaluate("document.querySelector('canvas')?.focus()");input(key,'keyDown');await delay(ms);input(key,'keyUp');await delay(180);}
async function lookAtSky(){await evaluate("document.querySelector('canvas')?.dispatchEvent(new MouseEvent('mousemove',{bubbles:true,buttons:1,movementY:-1000}))");await delay(1800);}
async function walkToCar(){window.focus();window.webContents.focus();await evaluate("document.querySelector('canvas')?.focus()");input('W','keyDown');try{await until('E correctly offers car entry after fuel and repairs',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.includes('Enter your car')"),45000);}finally{input('W','keyUp');}await delay(180);}
async function interaction(text){await click('.immersive-world__interact button',text);await delay(300);}
async function diagnostics(){const detail={};try{detail.gpuFeatures=app.getGPUFeatureStatus();detail.gpu=await app.getGPUInfo('basic');}catch(error){detail.gpuError=String(error);}try{detail.page=await evaluate("({ready:document.readyState,graphicsError:document.querySelector('.immersive-world__error')?.textContent,body:document.body.innerText.slice(-2200),canvases:Array.from(document.querySelectorAll('canvas')).map(canvas=>({width:canvas.width,height:canvas.height}))})");}catch(error){detail.pageError=String(error);}return detail;}
async function writeReport(){await fs.writeFile(path.join(output,'native-linux-result.json'),JSON.stringify(report,null,2));}
async function run(){
 try{
  await fs.mkdir(output,{recursive:true});await until('native career menu',()=>evaluate("!!document.querySelector('.career-slots')&&document.querySelector('.career-setup')?.getAttribute('aria-busy')==='false'"));
  if(process.env.SCOUT_LINUX_QA_REOPEN==='1'){
    const prior=JSON.parse(await fs.readFile(path.join(output,'native-linux-result.json'),'utf8'));assert.equal(prior.ok,true);Object.assign(report,prior);report.errors=[];
    const slots=await evaluate('window.scoutDesktop.listSaveSlots()');assert.equal(slots.length,3);assert(slots.every(slot=>slot.occupied));
    const reopened=await read(3);assert.deepEqual(reopened.immersion,prior.metrics.finalCareer);record('A fresh native process reloads the final durable career through the real preload');
    window.setBounds({x:0,y:0,width:640,height:480});await loadSlot(3);const viewport=await probe();assert(viewport.webgl&&viewport.paintedSamples>0&&viewport.distinctColors>1&&viewport.glError===0);report.metrics.reopenedViewport=viewport;record('Reopened career enters and paints the actual saved first-person world');await screenshot('reopened');
    await click('.immersive-world__tools button','Map');await click('.immersive-world__map button','Nearby');const nearby=await evaluate("Array.from(document.querySelectorAll('.map-place')).map(button=>({name:button.getAttribute('title'),left:parseFloat(button.style.left),top:parseFloat(button.style.top)}))");const player=reopened.immersion.player,origin={x:Math.max(0,Math.min(meta.world.width-2400,player.x-1200)),z:Math.max(0,Math.min(meta.world.depth-2000,player.z-1000))};const expected=meta.venues.filter(venue=>venue.parking.x>=origin.x&&venue.parking.x<=origin.x+2400&&venue.parking.z>=origin.z&&venue.parking.z<=origin.z+2000);assert.equal(nearby.length,expected.length);for(const venue of expected){const pin=nearby.find(pin=>pin.name===venue.name);assert(pin);assert(Math.abs(pin.left-(venue.parking.x-origin.x)/2400*100)<.01);assert(Math.abs(pin.top-(venue.parking.z-origin.z)/2000*100)<.01);}record('Nearby map clips distant venues and maps the real 2.4 km by 2 km viewport',{places:nearby,origin});await screenshot('reopened-nearby-map');await evaluate("document.querySelector('[aria-label=\"Close map\"]').click()");report.reopenObserved=true;report.stage='Completed';await writeReport();app.quit();return;
  }
  window.setBounds({x:0,y:0,width:1280,height:800});
  assert.equal(await evaluate('window.scoutDesktop.platform'),'linux-desktop');const slots=await evaluate('window.scoutDesktop.listSaveSlots()');assert.equal(slots.length,3);assert(slots.every(slot=>!slot.occupied));record('Real sandbox preload exposes three empty isolated native save slots');await screenshot('title');
  for(let slot=1;slot<=3;slot++){const saved=await evaluate(`window.scoutDesktop.saveCareer(${JSON.stringify(JSON.stringify(meta.seeds[slot-1]))},${slot})`);assert.equal(saved.ok,true);assert.equal((await read(slot)).style.name,'Linux QA '+slot);}record('Three schema-2 careers write and reload through the real native save store');
  await evaluate("localStorage.setItem('scout-immersive-preferences-v1',JSON.stringify({graphicsQuality:'low'}))");window.webContents.reload();await until('seeded native careers ready after reload',()=>evaluate("document.querySelector('.career-slot-main')?.textContent.includes('Linux QA 1')&&!document.querySelector('.career-slot-main')?.disabled"));
  await evaluate("HTMLCanvasElement.prototype.requestPointerLock=()=>Promise.reject(new Error('Headless QA has no physical pointer'));window.qaKeys=[];window.addEventListener('keydown',event=>window.qaKeys.push({type:event.type,key:event.key,hidden:document.hidden,trusted:event.isTrusted}));window.addEventListener('keyup',event=>window.qaKeys.push({type:event.type,key:event.key,hidden:document.hidden,trusted:event.isTrusted}));");report.limitations.push('Pointer capture is unavailable in the offscreen fixture; its request rejects immediately. Native mouse locking is not exercised.');
  window.setBounds({x:0,y:0,width:640,height:480});
  await loadSlot(1);const viewport=await probe();assert(viewport.webgl&&viewport.width>=640&&viewport.height>=480);assert.equal(viewport.glError,0);assert(viewport.paintedSamples>0&&viewport.distinctColors>1);report.metrics.viewport=viewport;record('Actual first-person world paints distinct visible WebGL2 pixels',viewport);await screenshot('on-foot');
  const initialRaw=await evaluate('window.scoutDesktop.loadCareer(1)');await interaction('Enter your car');await until('actual cockpit mode',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.toLowerCase().includes('step out')"));
  const clutter=await evaluate("({floatingDrivingHUD:!!document.querySelector('.immersive-world__driving'),floatingMph:!!document.querySelector('.immersive-world__speed'),floatingFuel:!!document.querySelector('.immersive-world__fuel'),localStorageCopy:document.querySelector('.scout-topbar')?.textContent.includes('locally'),fieldNotes:!!document.querySelector('.scout-quiet-objective')})");assert(Object.values(clutter).every(value=>value===false));record('Cockpit has no floating mph/fuel gauges or permanent storage/objective clutter',clutter);await screenshot('cockpit');
  await lookAtSky();report.limitations.push('The movement checks look upward through the game mouse-look handler to reduce visible geometry on the software GPU. These checks validate input/state/save behavior, not frame-rate performance.');window.focus();window.webContents.focus();await evaluate("document.querySelector('canvas').focus()");input('W','keyDown');await delay(4000);input('A','keyDown');await delay(1600);input('A','keyUp');input('W','keyUp');await delay(250);report.metrics.keyboardEvents=await evaluate('window.qaKeys');
  assert.equal(await evaluate('window.scoutDesktop.loadCareer(1)'),initialRaw);record('Live driving snapshots do not write the career every few seconds');
  const moving=await saveCurrent(1);assert.equal(moving.immersion.mode,'driving');assert(moving.immersion.vehicle.distance>1);assert(moving.immersion.vehicle.fuel<12);assert(Math.abs(moving.immersion.vehicle.heading)>.01);assert(Math.abs(moving.immersion.vehicle.speed)>.1);record('Native keyboard acceleration and steering produce real distance, fuel use and heading changes',{vehicle:moving.immersion.vehicle});await screenshot('settings');await resume();
  input('S','keyDown');await delay(300);input('S','keyUp');input('SPACE','keyDown');await delay(1700);input('SPACE','keyUp');await delay(250);await interaction('step out');await until('driver can step out after stopping',()=>evaluate("document.querySelector('.immersive-world__interact button')?.textContent.includes('Enter your car')"));
  const stopped=await saveCurrent(1);assert.equal(stopped.immersion.mode,'foot');assert.equal(stopped.immersion.vehicle.speed,0);assert(stopped.immersion.vehicle.distance>=moving.immersion.vehicle.distance);record('Brake, handbrake and grounded car exit preserve the driven career');await resume();
  await click('.immersive-world__tools button','Map');await until('regional map dialog',()=>evaluate("!!document.querySelector('.immersive-world__map')"));
  const map=await evaluate(`(()=>{const places=Array.from(document.querySelectorAll('.map-place')).map(button=>({name:button.getAttribute('title'),left:parseFloat(button.style.left),top:parseFloat(button.style.top)}));return {places,services:document.querySelectorAll('.map-service').length,regions:document.querySelectorAll('.map-region').length,nearbyToggle:Array.from(document.querySelectorAll('.immersive-world__map button')).some(button=>button.textContent.includes('Nearby'))};})()`);for(const venue of meta.venues){const pin=map.places.find(pin=>pin.name===venue.name);assert(pin,'Missing '+venue.name+' map pin');assert(Math.abs(pin.left-venue.parking.x/meta.world.width*100)<.01);assert(Math.abs(pin.top-venue.parking.z/meta.world.depth*100)<.01);}assert.equal(map.services,meta.services.filter(station=>station.locationId<0).length);assert(map.regions>=7&&map.nearbyToggle);record('Regional map uses the real 12 km by 10 km bounds and shows service destinations',map);await screenshot('regional-map');
  await click('.immersive-world__map button','Nearby');await screenshot('nearby-map');await evaluate("document.querySelector('[aria-label=\"Close map\"]').click()");await title();await loadSlot(1);const reloaded=await read(1);assert.deepEqual(reloaded.immersion.vehicle,stopped.immersion.vehicle);record('Save, title and career reload retain vehicle pose, fuel, damage and mileage');await title();
  await loadSlot(2);await interaction('Refuel');await until('physical pump service dialog',()=>evaluate("!!document.querySelector('.immersive-world__service')"));await screenshot('service');await click('.immersive-world__service-actions button','Fill the tank');await until('fuel purchase dialog closes',()=>evaluate("!document.querySelector('.immersive-world__service')"));const filled=await saveCurrent(2);assert.equal(filled.immersion.vehicle.fuel,12);assert.equal(filled.immersion.vehicle.damage,.42);assert.equal(filled.immersion.vehicle.distance,1523.4);assert(filled.cash<meta.seeds[1].cash);record('Fuel is purchased at the modeled pump without repairing damage or resetting mileage');await resume();
  await interaction('Refuel');await click('.immersive-world__service-actions button','Repair the compact');await until('repair dialog closes',()=>evaluate("!document.querySelector('.immersive-world__service')"));const repaired=await saveCurrent(2);assert.equal(repaired.immersion.vehicle.damage,0);assert.equal(repaired.immersion.vehicle.disabled,false);assert.equal(repaired.immersion.vehicle.distance,1523.4);assert.equal(repaired.immersion.vehicle.fuel,12);assert(repaired.cash<filled.cash);record('Paid repairs restore vehicle condition while keeping fuel and mileage');await resume();
  await lookAtSky();await walkToCar();await interaction('Enter your car');const entered=await saveCurrent(2);assert.equal(entered.immersion.mode,'driving');assert.equal(entered.immersion.vehicle.fuel,12);record('E prompt matches its action and the car can be re-entered after pump service');await title();
  await loadSlot(3);await until('stranded roadside assistance prompt',()=>evaluate("!!document.querySelector('.immersive-world__roadside')"));await screenshot('stranded');input('T','keyDown');input('T','keyUp');await until('native tow checkpoint',async()=>{const raw=await read(3);return raw.cash<meta.seeds[2].cash&&Math.hypot(raw.immersion.vehicle.x-meta.seeds[2].immersion.vehicle.x,raw.immersion.vehicle.z-meta.seeds[2].immersion.vehicle.z)>30;});const towed=await saveCurrent(3);assert.equal(towed.cash,meta.seeds[2].cash-150);assert.equal(towed.immersion.vehicle.distance,3142.7);assert.equal(towed.immersion.vehicle.fuel,2.25);assert.equal(towed.immersion.vehicle.damage,.93);assert.equal(towed.immersion.vehicle.disabled,true);assert.equal(towed.immersion.vehicle.gear,'R');assert.equal(towed.immersion.mode,'foot');record('Actual T roadside tow charges $150 and preserves fuel, damage, gear and mileage',{vehicle:towed.immersion.vehicle});await resume();await screenshot('towed');
  exitBaseline=await read(3);await lookAtSky();await hold('D',6000);await evaluate("window.dispatchEvent(new Event('scout:flush-field'))");assert.deepEqual((await read(3)).immersion.player,exitBaseline.immersion.player);record('Final walking movement remains live until the exit checkpoint');
  report.metrics.updateStatus=await evaluate('window.scoutDesktop.getUpdateStatus()');assert.equal(report.metrics.updateStatus.state,'unsupported');record('Linux development update manager does not block the offline local world',{state:report.metrics.updateStatus.state});
  report.diagnostics=await diagnostics();assert.deepEqual(report.errors,[]);await openSettings();await screenshot('save-and-exit');exitExpected=true;stage='Save and exit persists the newest live world snapshot';await writeReport();await click('.immersive-exit-button','Save and exit');
 }catch(error){report.ok=false;report.stage=stage;report.error=String(error.stack||error);try{report.diagnostics=await diagnostics();report.metrics.finalKeys=await evaluate('window.qaKeys');await screenshot('failure');}catch(captureError){report.captureError=String(captureError);}await writeReport();console.error(report.error);app.exit(1);}
}
app.on('ready',()=>console.log('QA Electron ready'));
app.on('browser-window-created',(_event,created)=>{console.log('QA real native window created');window=created;created.webContents.on('dom-ready',()=>console.log('QA renderer DOM ready'));created.webContents.on('preload-error',(_event,_path,error)=>report.errors.push('Preload: '+error));created.webContents.on('did-fail-load',(_event,code,description,_url,mainFrame)=>{if(mainFrame&&code!==-3)report.errors.push('Load '+code+': '+description);});created.webContents.on('render-process-gone',(_event,details)=>report.errors.push('Renderer: '+details.reason));created.webContents.on('console-message',({level,message})=>{if(level==='error'||level===3)report.errors.push(message);});created.once('ready-to-show',()=>{console.log('QA real native window ready to show');void run();});});
app.on('child-process-gone',(_event,details)=>{if(details.type==='GPU'&&!['normal-exit','clean-exit'].includes(details.reason))report.errors.push('GPU: '+details.reason);});
app.on('will-quit',()=>{if(!exitExpected)return;try{const raw=JSON.parse(syncFS.readFileSync(path.join(app.getPath('userData'),'save','slot-3','career.json'),'utf8'));assert(Math.hypot(raw.immersion.player.x-exitBaseline.immersion.player.x,raw.immersion.player.z-exitBaseline.immersion.player.z)>.2,'Save and exit must save the movement after the last checkpoint.');assert.equal(raw.immersion.vehicle.fuel,exitBaseline.immersion.vehicle.fuel);assert.equal(raw.immersion.vehicle.damage,exitBaseline.immersion.vehicle.damage);assert.equal(raw.immersion.vehicle.distance,exitBaseline.immersion.vehicle.distance);assert.equal(raw.immersion.mode,'foot');assert.deepEqual(report.errors,[]);report.metrics.finalCareer=raw.immersion;record('Real native Save and exit flushes the latest movement before app shutdown');report.nativeQuitObserved=true;report.ok=true;report.stage='Completed';}catch(error){report.ok=false;report.error=String(error.stack||error);report.stage=stage;}syncFS.writeFileSync(path.join(output,'native-linux-result.json'),JSON.stringify(report,null,2));});
const source=syncFS.readFileSync(main,'utf8');assert.equal((source.match(/webPreferences: \{/g)||[]).length,1);report.sourceMainSHA256=hash(source);report.distHTMLSHA256=hash(syncFS.readFileSync(path.join(root,'dist/index.html')));
assert.equal((source.match(/app\.requestSingleInstanceLock\(\)/g)||[]).length,1);report.limitations.push('The test bypasses the single-instance OS socket lock in memory because this Linux container blocks socket creation. Single-instance locking is not exercised.');
assert.equal((source.match(/screen\.getCursorScreenPoint\(\)/g)||[]).length,1);report.limitations.push('The headless fixture supplies a fixed cursor position because the headless Linux Ozone surface has no physical pointer. Desktop pointer and monitor selection are not exercised.');
report.limitations.push('A synthetic 1280 by 800 monitor is supplied in memory to the headless fixture. Physical display selection and fullscreen transitions are not exercised.');
const monitorExpression='({bounds:{x:0,y:0,width:1280,height:800},workArea:{x:0,y:0,width:1280,height:800}})';
report.limitations.push('Native titlebar options are omitted in the offscreen Linux fixture; OS titlebar styling is not exercised.');
const virtualSource=source.replace('webPreferences: {','webPreferences: { offscreen: true, backgroundThrottling: false,').replace('app.requestSingleInstanceLock()','true').replace('screen.getDisplayNearestPoint(screen.getCursorScreenPoint())',monitorExpression).replace('window: mainWindow, screen, preferences:','window: mainWindow, screen: {getDisplayMatching: () => '+monitorExpression+'}, preferences:').replace('...titleBarOptions(),','frame: false,').replace('function createWindow() {',"function createWindow() {console.log('QA enter real createWindow');").replace('const bounds = initialDisplay.mode',"console.log('QA monitor selected');const bounds = initialDisplay.mode").replace('mainWindow = new BrowserWindow({',"console.log('QA constructing native window');mainWindow = new BrowserWindow({").replace('const menu = applicationMenu',"console.log('QA beginning native services');const menu = applicationMenu").replace('registerBridge();',"console.log('QA registering native bridge');registerBridge();").replace('createWindow();',"console.log('QA services ready');createWindow();");const realMain=new Module(main,module);realMain.filename=main;realMain.paths=Module._nodeModulePaths(path.dirname(main));realMain._compile(virtualSource,main);
